services:

  mariadb:
    image: mariadb:11
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: gp_db
      MARIADB_USER: admin
      MARIADB_PASSWORD: ${MARIADB_ADMIN_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "-p$MARIADB_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: api
    volumes:
      - ./api:/app:delegated
      - ./api/logs:/app/logs
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    command: sh -c "npm install && npm run dev"
    networks:
      - app-network
    depends_on:
      mariadb:
        condition: service_healthy
    restart: unless-stopped
    env_file:
      - api/.env

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: client
    volumes:
      - ./client:/app
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    command: sh -c "npm install && npm run dev"
    networks:
      - app-network
    depends_on:
      - api
    restart: unless-stopped
    env_file:
      - client/.env

networks:
  app-network:
    driver: bridge
    
volumes:
  mariadb_data:
